service: serverless-backup-analysis

configValidationMode: warn

provider:
  name: aws
  runtime: python3.13
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::dovetail-backup-archive"
        - "arn:aws:s3:::dovetail-backup-archive/*"
  apiGateway:
    apiKeys:
      - name: ${opt:stage}-serverless-backup-analysis-key
    usagePlan:
          name: ${opt:stage}-serverless-backup-analysis-usage-plan
          quota:
            limit: 100000
            period: MONTH
          throttle:
            burstLimit: 200
            rateLimit: 100

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

package:
  include:
    - requirements.txt
    - backup/**
  exclude:
    - tests/**
    - requirements_test.txt
    - requirements_dev.txt

functions:
  backup-analysis:
    handler: backup.main.handler
    events:
      - http:
          path: /
          method: post
          cors: true
          private: true
